#!/usr/bin/env python3
"""
Generate the preview pages.

The chrome (unofficial ribbon, brand bar, the center's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "finder":  "8WBzX5PfGeJJPSB2chuumL",   # both pools, one day, a row per part of each pool; Teams menu
    "week":    "AAsteRpnoYZ3rQmcNYADY3",   # one pool, the whole week; Pools menu (opens on the Lap Pool)
    "lap":     "6zQTQzGiPiJDozzD145fnY",   # lap swim in both pools, plus meet closures
    "lessons": "mnHnXReBBoGwMDzFfExuxx",   # group lessons; Practice Groups menu picks a level
    "fit":     "CtqIZEw9hI2NZoYVkIBSmN",   # water aerobics; menu picks a class
    "team":    "BvBdRnqNVFYAaFbSTwo8WB",   # LCAC, Chatham Kraken, water polo, GCAT meets
    "open":    "iZNfkEIdBqtovLPzM2QenD",   # family open swim and water polo pickup
}

NAV = [
    ("index.html",          "Find a swim time"),
    ("week.html",           "The pool week"),
    ("lap-swim.html",       "Lap Swim"),
    ("open-swim.html",      "Open Swim"),
    ("swim-lessons.html",   "Swim Lessons"),
    ("water-aerobics.html", "Water Aerobics"),
    ("swim-teams.html",     "Swim Teams"),
]

SITE = "https://aquatic.chathamcountyga.gov"


def cal(key, title, cls="", caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="cal {cls}">
    <iframe width="100%" height="640" src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a Chatham County website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a Chatham County page. A mockup of the pool schedule for
  <a href="{SITE}/" target="_blank" rel="noopener">aquatic.chathamcountyga.gov</a> with live
  <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">CHATHAM COUNTY</span>Aquatic Center</a>
    <div class="tel">7240 Sallie Mood Dr, Savannah &middot; (912) 652-6793</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li><a href="{SITE}/Programs/SwimLessonsGroup" target="_blank" rel="noopener">Programs</a></li>
    <li><a href="{SITE}/Resources/AdmissionRates" target="_blank" rel="noopener">Admission/Rates</a></li>
    <li class="on"><a href="index.html">Hours</a></li>
    <li><a href="{SITE}/Resources/KnowBeforeYouGo" target="_blank" rel="noopener">Know Before You Go</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what one schedule for both pools at the Chatham
    County Aquatic Center could look like. Not affiliated with Chatham County.</p>
    <p>Read on 25 September 2026 from the center's <a href="{SITE}/Resources/Hours" target="_blank" rel="noopener">Hours</a>,
    <a href="{SITE}/" target="_blank" rel="noopener">home</a>,
    <a href="{SITE}/Programs/WaterAerobics" target="_blank" rel="noopener">Water Aerobics</a> and
    <a href="{SITE}/Programs/Kraken" target="_blank" rel="noopener">Kraken</a> pages, lesson registration on
    RecDesk, and the <a href="https://www.swimlcac.com/swimteam" target="_blank" rel="noopener">Low Country
    Aquatic Club</a> practice schedule. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics team</h2>
  <p>Everything on these calendars comes from what the center and its swim clubs publish. These are the
  places where two pages disagree, where a time isn't published, or where we had to make a call.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag gap">Gap</span>When are the &ldquo;SLOW&rdquo; times?</div>
      <div class="a">The Hours page asks swimmers who can't share a lane to &ldquo;plan your swim during a
      SLOW time&rdquo;, but no page says when those are. The club schedules suggest an answer: Low Country
      Aquatic Club is in the Lap Pool 6&ndash;7:30am Tuesday and Thursday, 2&ndash;3:30pm Monday to Thursday
      (homeschool groups) and 5:30&ndash;7pm Tuesday, Thursday and Friday, all while the pool is listed open
      for lap swim. How many lanes do they take?</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Evening open swim: 6:30 or 6:45?</div>
      <div class="a">The home page says open swim for families is 12&ndash;3:45pm and 6:30&ndash;8pm on
      weekdays. The Hours page reopens the Recreation Pool at 6:45pm. The calendar follows the Hours page.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Savannah Swim Team, GCAT and Savannah Masters</div>
      <div class="a">Three more clubs train here. The Savannah Swim Team's practice page is still the
      September 2024 schedule, GCAT lists its Savannah groups without times, and Savannah Masters links to
      a Facebook group. Only Low Country Aquatic Club and the center's own Chatham Kraken publish current
      times.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Saturday's asterisk, and Sundays</div>
      <div class="a">Saturday Lap Pool lap swim 12&ndash;6pm carries an asterisk the page never explains.
      Sunday isn't listed for either pool; the calendar treats the center as closed.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Water aerobics before October</div>
      <div class="a">The Water Aerobics page shows the October 2026 grid only, so September classes aren't on
      the calendar. Deep Water classes are in the Lap Pool; everything else is in the warm Recreation Pool.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Where is water polo?</div>
      <div class="a">The home page announces Saturday pickup games (youth 1&ndash;2pm, adults
      2:30&ndash;4pm) without saying which pool. We put them in the Lap Pool.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>How many short-course lanes?</div>
      <div class="a">Low Country Aquatic Club describes the Lap Pool as 8 lanes long course or 24 lanes
      short course, and the Recreation Pool as 6 lanes of 50 yards. The center's own history calls it a
      25-yard recreational pool, and pool directories list 20 short-course lanes.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Lap lanes, team lanes and program areas</div>
      <div class="a">No page says which lanes lap swim keeps while clubs, lessons and classes are in the
      water. We split the Lap Pool into lap lanes, team lanes and a program area, and the Recreation Pool
      into lap lanes, open swim, a lesson area and a class area, so they can sit side by side. Lessons are
      placed in the Recreation Pool, which the center calls ideal for them; registration doesn't say. In
      October, Monday and Wednesday Jr. Stroke Stars (6:45&ndash;7:15pm) overlaps Adult Stroke Stars
      (7&ndash;7:30pm) and is left flagged.</div>
    </li>
  </ul>
</section>

"""


HUB = f"""<section class="wrap hero">
  <div class="crumb">Aquatic Center &raquo; Hours</div>
  <h1>Find a swim time</h1>
  <p class="kicker">Lap Pool &middot; Recreation Pool &middot; one calendar</p>
  <p class="lead">Both pools on one calendar, a row for each part of each pool: lap lanes, the team lanes
  the swim clubs use, and the areas where lessons, classes and family swim happen. Pick a
  <strong>day</strong>, and use the <strong>Teams</strong> menu to show one program.</p>

{cal("finder", "Chatham County Aquatic Center — both pools, one day", "short")}

  <div class="try">
    <div><b>Laps at 4:30 on a weekday?</b>The Lap Pool is closed for swim team practice 4&ndash;5:30pm (to
    6pm Friday). The Recreation Pool keeps adult lap swim until 3:45, and all day on Fridays.</div>
    <div><b>A quiet lane?</b>Late morning to 2pm, Monday to Thursday, before the clubs arrive.
    Tuesday and Thursday at 6am the Gold group is already in the water.</div>
    <div><b>This Saturday?</b>The Lap Pool is closed 8am&ndash;5pm for the GCAT Pentathlon. The Recreation
    Pool keeps its regular hours.</div>
  </div>
</section>

<div class="trail">
  <div class="wrap">
    <h2>What does &ldquo;CLOSED&rdquo; mean?</h2>
    <p class="q">&ldquo;When can I get a lane to myself?&rdquo;</p>
    <p>The Hours page says to swim during a &ldquo;SLOW&rdquo; time, and lists the Lap Pool as
    <i>CLOSED</i> 4&ndash;5:30pm with no reason. The reason is on another site: that's when Low Country
    Aquatic Club's age-group swimmers practice. The same club's schedule also puts swimmers in the pool
    early on Tuesday and Thursday mornings, at 2pm Monday to Thursday and three evenings a week, while the
    Hours page shows the pool open for laps.</p>
    <p class="answer">Here the club practices sit <b>beside the lap lanes on the same calendar</b>, so a
    swimmer can see the busy times, and the quiet ones, before driving over. When a club changes its
    season, the staff change it once in an AI chat, and every page shows it.</p>
  </div>
</div>

<section class="wrap">
  <h2>By program</h2>
  <div class="cards">
    <a class="card" href="week.html"><div class="pic loc"></div><div class="body">
      <h3>The pool week</h3><p>One pool, Monday to Saturday, everything in the water.</p></div></a>
    <a class="card" href="lap-swim.html"><div class="pic lap"></div><div class="body">
      <h3>Lap Swim</h3><p>Lap swim in both pools, and the meets that close the Lap Pool.</p></div></a>
    <a class="card" href="open-swim.html"><div class="pic open"></div><div class="body">
      <h3>Open Swim</h3><p>Family swim in the warm Recreation Pool, and Saturday water polo.</p></div></a>
    <a class="card" href="swim-lessons.html"><div class="pic les"></div><div class="body">
      <h3>Swim Lessons</h3><p>September and October group lessons, from StarBabies to adults.</p></div></a>
    <a class="card" href="water-aerobics.html"><div class="pic fit"></div><div class="body">
      <h3>Water Aerobics</h3><p>19 classes a week: shallow, deep, arthritis, aqua yoga and H.I.I.T.</p></div></a>
    <a class="card" href="swim-teams.html"><div class="pic team"></div><div class="body">
      <h3>Swim Teams</h3><p>Low Country Aquatic Club, the Chatham Kraken, and meets.</p></div></a>
  </div>
</section>

{QUESTIONS}"""


WEEK = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; The pool week</div>
  <h1>The pool week</h1>
  <p class="kicker">Pick a pool from the menu</p>
  <p class="lead">Everything in one pool, Monday to Saturday: lap swim, swim team practice, lessons,
  classes and family swim. It opens on the Lap Pool; switch to the Recreation Pool or <strong>All</strong>.</p>

{cal("week", "Chatham County Aquatic Center — the pool week", "tall")}
</section>

<section class="wrap">
  <h2>The pools</h2>
  <div class="facts">
    <div><b>Lap Pool</b>50 meters, 7&ndash;9 feet deep, 78&ndash;82&deg;F. Set up short course (25 yards)
    all fall. Lap swim, swim teams, deep water aerobics.</div>
    <div><b>Recreation Pool</b>2&ndash;5 feet deep, 87&ndash;89&deg;F, zero-depth entry. Adult lap swim,
    family open swim (wristbands), lessons and warm-water classes.</div>
  </div>
</section>

"""


LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">Both pools &middot; circle swimming in shared lanes</p>
  <p class="lead">Lap swim in the 50-meter Lap Pool (set up 25 yards) and adult lap swim in the
  Recreation Pool, with the meets that close the Lap Pool. Use the <strong>Pools</strong> menu to show
  one pool.</p>

{cal("lap", "Chatham County Aquatic Center — lap swim", "tall")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>A closure on the home page</h2>
    <p>This Saturday's GCAT Pentathlon closes the Lap Pool from 8am to 5pm. It's announced at the top of
    the home page, not on the Hours page a lap swimmer checks.</p>
    <p class="answer">On this calendar the meet <b>replaces Saturday's lap swim for that one day</b>, and
    every page that shows the Lap Pool shows it.</p>
  </div>
</div>

"""


OPEN = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; Open Swim</div>
  <h1>Open Swim for Families</h1>
  <p class="kicker">Recreation Pool &middot; wristbands required</p>
  <p class="lead">Family swim in the warm, shallow Recreation Pool, weekday afternoons and evenings and
  Saturday afternoons, plus Saturday water polo pickup games. Swimmers 15 and younger need someone 18 or
  older with them.</p>

{cal("open", "Chatham County Aquatic Center — open swim")}
</section>

"""


LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; Swim Lessons</div>
  <h1>Group Swim Lessons</h1>
  <p class="kicker">Monthly sessions &middot; registration opens the 3rd Wednesday at noon</p>
  <p class="lead">StarBabies and SuperBabies, StarTots and SuperTots, group lessons for ages 3&ndash;10,
  11&ndash;14 and 15 and older, and the Stroke Stars classes. Classes that start at the same time are one
  block; use the <strong>Practice Groups</strong> menu to show one level.</p>

{cal("lessons", "Chatham County Aquatic Center — swim lessons")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Group classes in a list of 184</h2>
    <p>Registration lists every class as its own card, and most of the 184 are private lessons: one
    instructor, one time slot each. The group classes are mixed in, a September and an October copy of
    each.</p>
    <p class="answer">On a week, a parent sees that <b>Monday to Thursday a class starts every 45 minutes
    from 4 to 7pm</b>, and which levels start together.</p>
  </div>
</div>

"""


FIT = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; Water Aerobics</div>
  <h1>Water Aerobics</h1>
  <p class="kicker">October 2026 &middot; included with membership</p>
  <p class="lead">Shallow Water, Arthritis Therapy, Aqua Yoga and Aqua H.I.I.T. in the warm Recreation
  Pool, Deep Water in the Lap Pool. All classes are 45 minutes, ages 16 and up. Use the menu to show one
  class.</p>

{cal("fit", "Chatham County Aquatic Center — water aerobics")}
</section>

"""


TEAM = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Hours</a> &raquo; Swim Teams</div>
  <h1>Swim Teams</h1>
  <p class="kicker">Year-round clubs &middot; the Chatham Kraken</p>
  <p class="lead">Low Country Aquatic Club's seven groups, the center's own Chatham Kraken (Monday and
  Wednesday 5:30&ndash;6:30pm, fall season to November 18), Saturday water polo and GCAT meets. Use the
  <strong>Teams</strong> menu to show one.</p>

{cal("team", "Chatham County Aquatic Center — swim teams")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Four clubs, one pool, one schedule published</h2>
    <p>The USA Swim Teams page lists three clubs and a coach's email address for each. Their practice
    times are on their own sites: one current, one from 2024, one with no times at all.</p>
    <p class="answer">With the clubs on the center's calendar, <b>a coach, a parent and a lap swimmer all
    read the same schedule</b>, and the center knows who is in which lanes.</p>
  </div>
</div>

"""


PAGES = [
    ("index.html", "Find a swim time — Chatham County Aquatic Center (preview)",
     "Both pools at the Chatham County Aquatic Center on one live calendar.", HUB),
    ("week.html", "The pool week — Chatham County Aquatic Center (preview)",
     "Everything in one pool for the week.", WEEK),
    ("lap-swim.html", "Lap Swim — Chatham County Aquatic Center (preview)",
     "Lap swim in the Lap Pool and the Recreation Pool.", LAP),
    ("open-swim.html", "Open Swim — Chatham County Aquatic Center (preview)",
     "Family open swim and water polo pickup.", OPEN),
    ("swim-lessons.html", "Swim Lessons — Chatham County Aquatic Center (preview)",
     "Group swim lessons by level.", LESSONS),
    ("water-aerobics.html", "Water Aerobics — Chatham County Aquatic Center (preview)",
     "Water aerobics classes in both pools.", FIT),
    ("swim-teams.html", "Swim Teams — Chatham County Aquatic Center (preview)",
     "Swim club practice, the Chatham Kraken and meets.", TEAM),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        with open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(shell(slug, title, description, body))
        print("wrote", slug)
